# -*- coding: utf-8 -*-
"""CRAWLER_TESTE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QViSImuP1UlIFYd9ikHeFpGLdrrUF7fe
"""

# CÉLULA 1 - INSTALAÇÃO E CONFIGURAÇÃO =============================================================================================
!pip install tavily-python pandas google-generativeai

import os
import pandas as pd
from tavily import TavilyClient
import google.generativeai as genai
import requests
from bs4 import BeautifulSoup

# --- CHAVES API PARA TESTE ---
# --- CONFIGURAÇÃO TAVILY ---
TAVILY_API_KEY = "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"
os.environ["TAVILY_API_KEY"] = TAVILY_API_KEY
tavily = TavilyClient(api_key=TAVILY_API_KEY)

# --- CONFIGURAÇÃO GEMINI ---
# 1. Acesse https://aistudio.google.com/app/apikey
# 2. Crie uma nova chave de API e cole abaixo.
GEMINI_API_KEY = "AIzaSyD4r3kM0j2Xogo0fO1duy-RMafsNITG9Ts"
genai.configure(api_key=GEMINI_API_KEY)

# Configurações do modelo Gemini que usaremos
generation_config = {
  "temperature": 0.2,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 8192,
}

safety_settings = [
  {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
  {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
  {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
  {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
]

model = genai.GenerativeModel(model_name="gemini-1.5-flash",
                              generation_config=generation_config,
                              safety_settings=safety_settings)


# CÉLULA 2 - NOVA FUNÇÃO DE EXTRAÇÃO DO GEMINI =====================================================================================

def extrair_conteudo_com_ia(url):
    """
    Usa a API Gemini para analisar o HTML de uma URL e extrair o conteúdo principal.
    """
    print(f"\nProcessando com IA: {url}")

    # Cabeçalho para simular um navegador e evitar bloqueios (erro 403)
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    try:
        response = requests.get(url, headers=headers, timeout=20)
        response.raise_for_status()

        # Usamos BeautifulSoup para uma pré-limpeza leve, tirando scripts e styles
        soup = BeautifulSoup(response.text, 'html.parser')
        for tag in soup(['script', 'style', 'nav', 'header', 'footer']):
            tag.decompose()

        html_pre_limpo = soup.get_text(separator='\n', strip=True)

        # Se o texto for muito curto, nem gasta a API
        if len(html_pre_limpo) < 500:
             print("--> Descartado: Conteúdo pré-limpeza muito curto.")
             return None

        # Monta o prompt para a IA
        prompt_parts = [
            "Você é um especialista em extração de dados de páginas web.",
            "Analise o seguinte texto extraído de um HTML e retorne APENAS o texto limpo e coeso do artigo principal.",
            "Ignore qualquer texto de menu, anúncios, links de 'leia também', avisos de cookies ou rodapés.",
            "Se o conteúdo não parecer um artigo de notícia completo (ex: é apenas uma lista de links, uma galeria de fotos ou uma página de erro), retorne EXATAMENTE a palavra 'NAO_EH_ARTIGO'.",
            "\n--- INÍCIO DO TEXTO DA PÁGINA ---\n",
            html_pre_limpo[:15000],  # Limita o tamanho para não exceder limites da API
            "\n--- FIM DO TEXTO DA PÁGINA ---\n",
            "ARTIGO EXTRAÍDO:",
        ]

        # Chama a API Gemini
        response_ia = model.generate_content(prompt_parts)
        texto_extraido = response_ia.text.strip()

        if "NAO_EH_ARTIGO" in texto_extraido or len(texto_extraido) < 250:
            print("--> Veredito da IA: Não é um artigo válido.")
            return None

        print("--> Veredito da IA: Artigo extraído com sucesso.")
        return {
            "link": url,
            "texto": texto_extraido
        }

    except Exception as e:
        print(f"--> [!] Erro ao processar a URL com IA: {e}")
        return None

# CÉLULA 3 - ORQUESTRAÇÃO FINAL E EXECUÇÃO ========================================================================================

query = "notícias recentes sobre educação no Distrito Federal"
print(f"Buscando no Tavily pela query: '{query}'")
response_tavily = tavily.search(query=query, search_depth="advanced", max_results=7)
urls_tavily = response_tavily['results']
print(f"\nBusca concluída! {len(urls_tavily)} URLs candidatas encontradas.")

# 2. Processamento com a IA
artigos_finais = []
for item in urls_tavily:
    url = item.get('url')
    if not url:
        continue

    # Chama nossa nova função inteligente
    resultado_ia = extrair_conteudo_com_ia(url)

    if resultado_ia:
        # Adiciona o título e a fonte que o Tavily já nos deu
        resultado_ia['titulo'] = item.get('title', 'Título não encontrado')
        resultado_ia['fonte'] = item.get('source', url.split('/')[2])
        artigos_finais.append(resultado_ia)

# 3. Exibição dos resultados
print("\n" + "="*50)
print(f"Processo finalizado. {len(artigos_finais)} artigos válidos foram extraídos pela IA.")
print("="*50)

if artigos_finais:
    df = pd.DataFrame(artigos_finais)
    df = df[['fonte', 'titulo', 'link', 'texto']] # Reordenando colunas
    pd.set_option('display.max_colwidth', 80)
    display(df)
else:
    print("\nNenhum artigo válido foi extraído pela IA nos links retornados pela busca.")